[technote]
id = "DMTN-321"
series_id = "DMTN"
canonical_url = "https://dmtn-321.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-321"
github_default_branch = "main"
date_created = 2025-07-14T17:54:16Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Frossie"
name.family = "Economou"
internal_id = "economouf"
orcid = "https://orcid.org/0000-0002-8333-7615"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "Tucson"
